services:
  - type: web
    name: paper-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000

  - type: static_site
    name: paper-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: paper-backend
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
